-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 12:33:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `count_workmates` INT NULL,
  `title` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`workmate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workmate` (
  `id_workmate` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `unit_id` INT NOT NULL,
  PRIMARY KEY (`id_workmate`, `unit_id`),
  UNIQUE INDEX `id_workmate_UNIQUE` (`id_workmate` ASC) VISIBLE,
  INDEX `fk_workmate_unit_idx` (`unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_workmate_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `mydb`.`unit` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`month` (
  `month_name` VARCHAR(45) NOT NULL,
  `month_number` INT NOT NULL,
  `count_days` INT NOT NULL,
  `count_work_days` INT NOT NULL,
  UNIQUE INDEX `month_name_UNIQUE` (`month_name` ASC) VISIBLE,
  PRIMARY KEY (`month_number`))
ENGINE = InnoDB;

-----------------------------------------------------
-- Table `mydb`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unit_id` INT NOT NULL,
  `month_month_number` INT NOT NULL,
  PRIMARY KEY (`id`, `month_month_number`, `unit_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_table_unit1_idx` (`unit_id` ASC) VISIBLE,
  INDEX `fk_table_month1_idx` (`month_month_number` ASC) VISIBLE,
  CONSTRAINT `fk_table_unit1`
    FOREIGN KEY (`unit_id`)
    REFERENCES `mydb`.`unit` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table_month1`
    FOREIGN KEY (`month_month_number`)
    REFERENCES `mydb`.`month` (`month_number`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`sick_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sick_document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `beginning_disease` DATE NOT NULL,
  `end_disease` DATE NOT NULL,
  `count_days_disease` INT NOT NULL,
  `workmate_id_workmate` INT NOT NULL,
  PRIMARY KEY (`id`, `workmate_id_workmate`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_sick_document_workmate1_idx` (`workmate_id_workmate` ASC) VISIBLE,
  CONSTRAINT `fk_sick_document_workmate1`
    FOREIGN KEY (`workmate_id_workmate`)
    REFERENCES `mydb`.`workmate` (`id_workmate`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`travel_permit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`travel_permit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `beginning_travel` DATE NOT NULL,
  `end_disease` DATE NOT NULL,
  `count_days_travel` INT NOT NULL,
  `workmate_id_workmate` INT NOT NULL,
  PRIMARY KEY (`id`, `workmate_id_workmate`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_travel_permit_workmate1_idx` (`workmate_id_workmate` ASC) VISIBLE,
  CONSTRAINT `fk_travel_permit_workmate1`
    FOREIGN KEY (`workmate_id_workmate`)
    REFERENCES `mydb`.`workmate` (`id_workmate`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vacation_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vacation_application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `beginning_vacation` DATE NOT NULL,
  `end_vacation` DATE NOT NULL,
  `count_days_vacation` INT NOT NULL,
  `workmate_id_workmate` INT NOT NULL,
  PRIMARY KEY (`id`, `workmate_id_workmate`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_vacation_application_workmate1_idx` (`workmate_id_workmate` ASC) VISIBLE,
  CONSTRAINT `fk_vacation_application_workmate1`
    FOREIGN KEY (`workmate_id_workmate`)
    REFERENCES `mydb`.`workmate` (`id_workmate`)
	ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
